server:
  port: 8080
  shutdown: graceful

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/migration/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/wotf_db?stringtype=unspecified
    username: wotf_user
    password: wotf_pass
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
  lifecycle:
    timeout-per-shutdown-phase: 20s

logging:
  level:
    root: info
